import { useEffect, useState } from 'react';
import { ArrowUpRight, BrainCircuit, MoreHorizontal, TrendingUp } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, query } from '../api';

const zero={customers:{total:0},revenue:{totalEvents:0,totalAmount:0},signals:{total:0,active:0},recommendations:{total:0,proposed:0,accepted:0},forecasts:{total:0}};
const money=(n,c)=>{if(!Number.isFinite(n)||typeof c!=='string'||!/^[A-Z]{3}$/.test(c))return 'Unknown currency';return new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:0}).format(n);};
const normalizeCurrency=(value)=>typeof value==='string'?value.trim().toUpperCase():null;
const formatRecommendationImpact=(item)=>{const currency=normalizeCurrency(item?.currency);if(!currency||!Number.isFinite(item?.expectedImpact))return 'Unknown currency';return money(item.expectedImpact,currency);};
function Metric({label,value,detail}){return <article className="metric-card"><div className="metric-label"><span>{label}</span><MoreHorizontal size={17}/></div><strong>{value}</strong><div className="metric-trend"><span><TrendingUp size={14}/> Live</span><em>{detail}</em></div></article>}
export default function Dashboard({token,workspaceId,user}){
 const [overview,setOverview]=useState(zero),[revenue,setRevenue]=useState({byCurrency:[]}),[recommendations,setRecommendations]=useState([]),[forecasts,setForecasts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setError('');Promise.all([api(query('/analytics/overview',workspaceId),{token}),api(query('/analytics/revenue',workspaceId),{token}),api(query('/recommendations',workspaceId),{token}),api(query('/forecasts',workspaceId),{token})]).then(([o,r,re,f])=>{if(alive){setOverview(o.overview||o);setRevenue(r.revenue||r);setRecommendations(re.recommendations||[]);setForecasts(f.forecasts||[]);}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[token,workspaceId]);
 const chart=[...(revenue.byCurrency||[])].map(x=>({name:x.currency,revenue:x.totalRevenue||0}));
 const recentRevenue=revenue.recent||[];
 const opportunities=recommendations.slice(0,3);
 const recommendationCurrencies=Array.from(new Set((recommendations||[]).map(item=>normalizeCurrency(item.currency)).filter(Boolean))).sort();
 return <div className="page-enter"><header className="page-header"><div><p className="eyebrow">Live workspace data <span className="live-dot"/> MongoDB connected</p><h1>Good evening, {user?.name?.split(' ')[0]||'there'}</h1><p className="page-subtitle">This dashboard is reading protected data from your GrowthPilot backend.</p></div><button className="primary-button" onClick={()=>document.querySelector('.workspace-switcher button')?.click()}><BrainCircuit size={17}/> Change workspace</button></header>
 {error?<div className="empty-state"><h2>Could not load dashboard</h2><p>{error}</p></div>:loading?<div className="loading-screen">Loading live analytics…</div>:<>
 <section className="metrics-grid"><Metric label="Customers" value={overview.customers?.total||0} detail="in this workspace"/><Metric label="Total revenue" value={overview.revenue?.currencyMode==='multiple'?'Multiple currencies':overview.revenue?.currencyMode==='none'?'No currency':money(overview.revenue?.totalAmount,overview.revenue?.currency)} detail={overview.revenue?.currencyMode==='multiple'?'multiple currencies':overview.revenue?.currencyMode==='none'?'no currency':'persisted revenue'}/><Metric label="Revenue events" value={overview.revenue?.totalEvents||0} detail="persisted events"/><Metric label="Active signals" value={overview.signals?.active||0} detail={`${overview.signals?.total||0} total signals`}/><Metric label="Recommendations" value={overview.recommendations?.total||0} detail={`${overview.recommendations?.proposed||0} pending`}/></section>
 <div className="content-grid"><section className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Financial data</p><h2>Revenue by currency</h2></div><button className="icon-button"><MoreHorizontal size={18}/></button></div><div className="chart-wrap">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d4145a" stopOpacity={.35}/><stop offset="100%" stopColor="#d4145a" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="revenue" stroke="#e11d5a" strokeWidth={3} fill="url(#revenueFill)"/></AreaChart></ResponsiveContainer>:<div className="empty-chart">No revenue events yet. Add data through your API and refresh.</div>}</div></section>
 <section className="panel insight-panel"><div className="insight-icon"><BrainCircuit size={21}/></div><p className="eyebrow">Workspace summary</p><h2>{overview.signals?.total?`${overview.signals.active||0} active signals need attention`:'Your workspace is ready for data'}</h2><p className="body-copy">Recommendations and forecasts shown here are real records from your database. No fake AI values are mixed into the live counts.</p><div className="impact-row"><div><span>Accepted</span><strong>{overview.recommendations?.accepted||0}</strong></div><div><span>Forecasts</span><strong>{forecasts.length}</strong></div></div></section></div>
 <div className="content-grid lower-grid"><section className="panel opportunities-panel"><div className="panel-heading"><div><p className="eyebrow">From your backend</p><h2>Recommendations</h2></div></div>{opportunities.length?opportunities.map(item=><div className="opportunity" key={item.id}><div className="opportunity-mark pink"><ArrowUpRight size={17}/></div><div className="opportunity-copy"><strong>{item.title}</strong><span>{item.recommendedAction}</span></div><div className="opportunity-stats"><b>{item.expectedImpact!=null?(recommendationCurrencies.length>1?'Multiple currencies':formatRecommendationImpact(item)):'—'}</b><span>{item.confidence!=null?`${Math.round(item.confidence*100)}% confidence`:'No confidence score'}</span></div><span className={`priority ${item.priority||'medium'}`}>{item.priority||'normal'}</span></div>):<div className="empty-inline">No recommendations stored yet.</div>}</section><section className="panel segment-panel"><p className="eyebrow">Recent revenue activity</p><h2>{recentRevenue.length?'Latest events':'No revenue activity'}</h2>{recentRevenue.length?<div className="segment-list">{recentRevenue.map((item,index)=><span key={`${item.occurredAt}-${index}`}><b>{money(item.amount,item.currency)}</b><small>{item.source||'Workspace event'} · {new Date(item.occurredAt).toLocaleDateString()}</small></span>)}</div>:<div className="empty-inline">No revenue events yet.</div>}</section></div></>}
 </div>
}
